server:
  port: 8765
spring:
  application:
    name: orange-feign
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/