server:
    port: 80
#数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://62.234.49.33:3306/haoqi?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 7777
    type: com.alibaba.druid.pool.DruidDataSource
#热部署生效
  devtools:
    restart:
      enabled: true
  data:
    mongodb:
      uri: mongodb://62.234.49.33:27017/test
#redis
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 62.234.49.33
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: 7777
    pool:
    #连接池最大连接数（使用负值表示没有限制）
      max-active: 8
    # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
    # 连接池中的最大空闲连接
      max-idle: 8
    # 连接池中的最小空闲连接
      min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 1000
#rabbitmq
  application:
    name: spirng-boot-rabbitmq-sender
  rabbitmq:
    host: 62.234.49.33
    port: 5672
    username: hq
    password: 1
mybatis:
  mapperlocations: classpath*:mapper/*Mapper.xml
#日志级别改为debug可以显示sql语句,logging.level后为存放mapper接口的包
#logging:
#  level:
#    com.mr.dao.*: debug
#pagehelper分页插件配置
#pagehelper:
#  helperDialect: mysql

