server:
  port: 8082
spring:
  datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://62.234.49.33:3306/haoqi?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
        username: root
        password: 7777
        type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  mapperlocations: classpath*:mapper/*Mapper.xml
logging:
  level:
    com.mr.*.*.mapper: debug
pagehelper:
  helperDialect: mysql