server:
  port: 8762
spring:
  application:
    name: orange-search #服务的名字
  data:
    #solr
    solr:
      host: http://127.0.0.1:8080/solr/search
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/orangetest?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
      username: root
      password: 7777
      type: com.alibaba.druid.pool.DruidDataSource
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ #链接注册中心的地址
mybatis:
  mapperlocations: classpath*:mapper/*Mapper.xml
#  #扫面domain包中的实体类并起别名
#  config-location: classpath:mybatis-config.xml
#日志级别改为debug可以显示sql语句,logging.level后为存放mapper接口的包
logging:
  level:
    com.mr.dao.*: debug
#pagehelper分页插件配置
pagehelper:
  helperDialect: mysql