server:
  port: 8762
spring:
  application:
    name: orange-search #\u670D\u52A1\u7684\u540D\u5B57
  data:
    #solr
    solr:
      host: http://127.0.0.1:8080/solr/search
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ #\u94FE\u63A5\u6CE8\u518C\u4E2D\u5FC3\u7684\u5730\u5740
