server:
  port: 8763
spring:
  application:
    name: orange-order #\u670D\u52A1\u7684\u540D\u5B57
  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/ #链接注册中心的地址